# Classical backtracking algorithm

In [1]:
import numpy as np
from math import sqrt

In [4]:
def in_row(grid, row, val):
    grid_size = len(grid)
    for i in range(grid_size):
        if grid[row, i] == val:
            return True

    return False


def in_column(grid, column, val):
    grid_size = len(grid)
    for i in range(grid_size):
        if grid[i, column] == val:
            return True
    return False


def in_box(grid, row, column, val):
    grid_size = len(grid[0])
    box_size = round(sqrt(grid_size))
    row_0 = (row//box_size) * box_size
    column_0 = (column//box_size) * box_size 
    for r in range(box_size):
        for c in range(box_size):
            if grid[row_0 + r, column_0 + c] == val:
                return True        
    return False


def is_possible(grid, row, column, val):
    return (not in_row(grid, row, val)
            and not in_column(grid, column, val)
            and not in_box(grid, row, column, val))

def solve(grid, solutions = []):
    grid_size = len(grid[0])
    for r in range(grid_size):
        for c in range(grid_size):
            if grid[r, c] == -1:
                for val in range(grid_size):
                    if is_possible(grid, r, c, val):
                        grid[r, c] = val
                        solve(grid, solutions)
                        grid[r, c] = -1
                return
    solutions.append(grid)

In [12]:
sudoku = np.array([
    [-1, -1, -1, -1],
    [-1, -1, -1, -1],
    [-1, -1, -1, -1],
    [-1, -1, -1, -1]
])

solutions = []
solve(sudoku, solutions)

for i in range(len(solutions)):
    print(f"Solution #{i}")
    print(solutions[i], "\n")

Solution #0
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #1
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #2
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #3
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #4
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #5
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #6
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #7
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #8
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #9
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #10
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #11
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #12
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] 

Solution #13
[[-1 -1 -

# Quantum algorithm

In [ ]:
#TODO